title: "Stripe Connect fundamentals Series"
summary: "dev.to/stripe のStripe Connect fundamentals Seriesを日本語化していきます。２章以降は随時追加予定"
topics: ['stripe']
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - episode1
  - episode2
  - episode3
  - episode4
