title: "Next.js(App Router)とStripeを利用した、ローコードでシンプルなECサイト構築チュートリアル"
summary: このワークショップでは、StripeとNext.jsを利用したシンプルなe-commerceサイトを作る方法を学びます。 "
topics: ['stripe', 'nextjs', 'react']
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - step0
  - step1
  - step2
  - step3
  - step4
  - wrapup
