title: "Stripe Payment Linksで始める、ノーコードなオンライン決済入門"
summary: 
  StripeのPayment Linksを利用すると、コードを書かずにクレジットカードなどの決済を受け付けるURLを作成できます。
  また、Dashboardで設定を行うことで、割引やGoogle Analyticsでのトラッキング、QRコード発行なども簡単に行えます。

  この書籍では、Stripe Payment Linksの基本的な使い方と、ZapierやGoogle Analytics、Stripe Appsなどを組み合わせた、ノーコードなシステム連携について紹介します。
  
  サービスやアプリを新しくスタートする際に欠かせない「オンライン決済」を、Payment Linksでシンプルにはじめましょう。
topics: ['stripe', 'nocode']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap0
  - chap1
  - chap2
  - chap3
  - chap4
  - chap5
  - chap6
  - chapx
